// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzcpjkdhjxfrmquwadfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6Y3Bqa2Roanhmcm1xdXdhZGZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNDM0MjAsImV4cCI6MjA1ODgxOTQyMH0.WhJoVC0zljd219AAUSlk7h1cHyDlDKiFWC-AjVcFRvc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);